sudo: false
language: python
python:
- 3.5
env:
- TOX_ENV="py3.5"
- TOX_ENV="pep8"
install:
- pip install tox
- pip install codecov
script:
- tox -e $TOX_ENV
after_success:
- codecov
deploy:
  provider: pypi
  user: denis_makogon
  password:
    secure: WMKKnV3zTtxqFhoM8ucyvzxXeDUwbIpQKq99dhGiAEluUIqlZGm/a8XjUUz3dVUasz4dCHP52htPMwXL/19Ue5xe9pw0CX3swcDMqoXzysioI+25VhU8b5A/v6mXFfq1gz6PCExO7DB2KOexaDMfQo5UyRMx9bslbhz3gRg9ceNKWWsKL7sf5RU4WtzaqJavE60hbJTeDyZ7RuEfASxtQCwvJidcttihf92vlivkP30dk7jAmmaPOdQg3KUnYPosvtM0Qp2dXPHKhiv2/23WS9CRW3r26vZdPJwZQ7N2TE+RpdrwSZEafSwzj+QVfi9dbacrDJ2bNwsGtelbIT09pQK0sn2BGnZ6Idxulwl6vvKp8ZgReZVqPWn03Y2dAjRehkEaftAx+8knK97T/SIgZ4BZWIhoMoMAQmEY4YwxOLZFw+lpvumI2ThTLP2tbuEnH3cSQXe6uMpcI2J+SpQAk6qj1mGIEkEtACdJf/mcM6PZNyvJSwkO+rGPCVj/O7+NjTkzpIXsZwFmLu8Mzg1HGMKxJafQUCb9FMw6fs9ntsQzo006oM6DdZu5dQXJ7m/DLzER1yBxQrXuaogQwB8dFHvJJWO5kUz/R9N6xSW6gfjBAsgODfqzZW58cd2b9kVNDUOgt9dnjLJboL8XkrkMPDsvuSzDFBP6Hl3SQQ2kuZY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: denismakogon/hotfn-py
