sudo: false
language: python
python:
- 3.5
env:
- TOX_ENV="py35"
- TOX_ENV="pep8"
install:
- pip install tox
- pip install codecov
script:
- tox -e $TOX_ENV
- make test-pipe
after_success:
- codecov
deploy:
  provider: pypi
  user: denis_makogon
  password:
    secure: QgoQK/qfiSjOjrKziADPERcbkcOaf89j3UpGnRMTBmCLtEJVszoJAh/jxfUjRyHJVMofiCui6PxpjQcjIiqnyU/lIqpXsuD1mNKb3zLnVjwe0G/+B/mOVV9gbnwIlszu7UTVLSZUXELnWxQ48zEZ3OSItFB935uURSJ6a0WcMtjDoOpPPVzEXAMUqKvEJWfCylGhNtXlyqPH7Pq3imMYLJf8v8HBFyUQTmI0muMz7nSCxIn0ZXC+bexBRk1gqzwMEoYLwZUwlPrgnX6TON7X+0HzbTHBVXqPYS/AT6dmGAiq+riluJqRmTwzKJXdJcd/E0o68LCBE6IvDDFoTrAGBKofMn5ObMaUlydPBvgmqx8S/VO7j7piNpy8ko5IBclWNeV9JilcWSxqZux8+FLdS8leYnqmiNT3cy2cdJA24xQI5biZ95ILkwkycXm92eOATxpN9i5guJLT3I1DjkpyiRdNwSLLXC/SZldiDaBcQqXJafs7nocZZG1ZVS5ykW5VpOXxlC96hw3BMIPyUfJjZW4xpD//4o2M7lIWIXoKTmQ0u9MRxjE4d2ufodnP0qf4lQo3rLuWzpbg0tswQoO3Fn/xWYyGCLtCGFgNUGHjZP3LbmKomJGtQzjVF9ZJeuBKBpDXsXMs/i2q4NWeS7QI+5qTuVZ2seq9GBPHOOHrHUg=
